# Generated by Django 5.2.7 on 2025-11-14 17:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_alter_post_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="created_at",
            new_name="created_date",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="content",
            new_name="text",
        ),
    ]
