# Generated by Django 5.2.7 on 2025-11-14 18:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0003_rename_created_at_post_created_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="published_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="created_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="post",
            name="text",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
