# Generated by Django 5.2.7 on 2025-11-15 07:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0004_post_published_date_alter_post_created_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="text",
            new_name="content",
        ),
    ]
